interface Column {
  id: "name" | "description";
  label: string;
  minWidth?: number;
  align?: "right";
  format?: (value: number) => string;
}

export const columns: readonly Column[] = [
  { id: "name", label: "Name", minWidth: 1 },
  { id: "description", label: "Description", minWidth: 100 },
];

interface Data {
  name: string;
  description: string;
}

function createData(name: string, description: string): Data {
  return { name, description };
}

export const rows = [
  createData("India", "IN"),
  createData("China", "CN"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("China", "CN"),
  createData("China", "CN"),
  createData("China", "CN"),
  createData("China", "CN"),
  createData("China", "CN"),
  createData("China", "CN"),
  createData("China", "CN"),
  createData("China", "CN"),
  createData("China", "CN"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "IT"),
  createData("Italy", "50"),
];
